# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: f:/Documents/GitHub/zynq-freertos-sandbox/2023.2/zybo-z7-20/hw-proj1/hw-proj1.srcs/sources_1/bd/hw_proj1/ip/hw_proj1_xbar_0/hw_proj1_xbar_0.xci
# IP: The module: 'hw_proj1_xbar_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: f:/Documents/GitHub/zynq-freertos-sandbox/2023.2/zybo-z7-20/hw-proj1/hw-proj1.gen/sources_1/bd/hw_proj1/ip/hw_proj1_xbar_0/hw_proj1_xbar_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'hw_proj1_xbar_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: f:/Documents/GitHub/zynq-freertos-sandbox/2023.2/zybo-z7-20/hw-proj1/hw-proj1.srcs/sources_1/bd/hw_proj1/ip/hw_proj1_xbar_0/hw_proj1_xbar_0.xci
# IP: The module: 'hw_proj1_xbar_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: f:/Documents/GitHub/zynq-freertos-sandbox/2023.2/zybo-z7-20/hw-proj1/hw-proj1.gen/sources_1/bd/hw_proj1/ip/hw_proj1_xbar_0/hw_proj1_xbar_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'hw_proj1_xbar_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
