# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: imports/new/main_constraints.xdc

# Block Designs: bd/hw_proj1/hw_proj1.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==hw_proj1 || ORIG_REF_NAME==hw_proj1} -quiet] -quiet

# IP: bd/hw_proj1/ip/hw_proj1_processing_system7_0_0/hw_proj1_processing_system7_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==hw_proj1_processing_system7_0_0 || ORIG_REF_NAME==hw_proj1_processing_system7_0_0} -quiet] -quiet

# IP: bd/hw_proj1/ip/hw_proj1_axi_gpio_0_0/hw_proj1_axi_gpio_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==hw_proj1_axi_gpio_0_0 || ORIG_REF_NAME==hw_proj1_axi_gpio_0_0} -quiet] -quiet

# IP: bd/hw_proj1/ip/hw_proj1_xbar_0/hw_proj1_xbar_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==hw_proj1_xbar_0 || ORIG_REF_NAME==hw_proj1_xbar_0} -quiet] -quiet

# IP: bd/hw_proj1/ip/hw_proj1_ps7_0_axi_periph_0/hw_proj1_ps7_0_axi_periph_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==hw_proj1_ps7_0_axi_periph_0 || ORIG_REF_NAME==hw_proj1_ps7_0_axi_periph_0} -quiet] -quiet

# IP: bd/hw_proj1/ip/hw_proj1_rst_ps7_0_50M_0/hw_proj1_rst_ps7_0_50M_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==hw_proj1_rst_ps7_0_50M_0 || ORIG_REF_NAME==hw_proj1_rst_ps7_0_50M_0} -quiet] -quiet

# IP: bd/hw_proj1/ip/hw_proj1_axi_gpio_1_0/hw_proj1_axi_gpio_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==hw_proj1_axi_gpio_1_0 || ORIG_REF_NAME==hw_proj1_axi_gpio_1_0} -quiet] -quiet

# IP: bd/hw_proj1/ip/hw_proj1_auto_pc_0/hw_proj1_auto_pc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==hw_proj1_auto_pc_0 || ORIG_REF_NAME==hw_proj1_auto_pc_0} -quiet] -quiet

# XDC: f:/Documents/GitHub/zynq-freertos-sandbox/2023.2/zybo-z7-20/hw-proj1/hw-proj1.gen/sources_1/bd/hw_proj1/hw_proj1_ooc.xdc
